#!/bin/bash
python eda_script.py --alpha=.1 --num_aug=1 --input=train.csv --da_type=sr
python eda_script.py --alpha=.1 --num_aug=3 --input=train.csv --da_type=sr
python eda_script.py --alpha=.1 --num_aug=5 --input=train.csv --da_type=sr
python eda_script.py --alpha=.3 --num_aug=1 --input=train.csv --da_type=sr
python eda_script.py --alpha=.3 --num_aug=3 --input=train.csv --da_type=sr
python eda_script.py --alpha=.3 --num_aug=5 --input=train.csv --da_type=sr
python eda_script.py --alpha=.5 --num_aug=1 --input=train.csv --da_type=sr
python eda_script.py --alpha=.5 --num_aug=3 --input=train.csv --da_type=sr
python eda_script.py --alpha=.5 --num_aug=5 --input=train.csv --da_type=sr
python eda_script.py --alpha=.1 --num_aug=1 --input=train.csv --da_type=ri
python eda_script.py --alpha=.1 --num_aug=3 --input=train.csv --da_type=ri
python eda_script.py --alpha=.1 --num_aug=5 --input=train.csv --da_type=ri
python eda_script.py --alpha=.3 --num_aug=1 --input=train.csv --da_type=ri
python eda_script.py --alpha=.3 --num_aug=3 --input=train.csv --da_type=ri
python eda_script.py --alpha=.3 --num_aug=5 --input=train.csv --da_type=ri
python eda_script.py --alpha=.5 --num_aug=1 --input=train.csv --da_type=ri
python eda_script.py --alpha=.5 --num_aug=3 --input=train.csv --da_type=ri
python eda_script.py --alpha=.5 --num_aug=5 --input=train.csv --da_type=ri
python eda_script.py --alpha=.1 --num_aug=1 --input=train.csv --da_type=rs
python eda_script.py --alpha=.1 --num_aug=3 --input=train.csv --da_type=rs
python eda_script.py --alpha=.1 --num_aug=5 --input=train.csv --da_type=rs
python eda_script.py --alpha=.3 --num_aug=1 --input=train.csv --da_type=rs
python eda_script.py --alpha=.3 --num_aug=3 --input=train.csv --da_type=rs
python eda_script.py --alpha=.3 --num_aug=5 --input=train.csv --da_type=rs
python eda_script.py --alpha=.5 --num_aug=1 --input=train.csv --da_type=rs
python eda_script.py --alpha=.5 --num_aug=3 --input=train.csv --da_type=rs
python eda_script.py --alpha=.5 --num_aug=5 --input=train.csv --da_type=rs
python eda_script.py --alpha=.1 --num_aug=1 --input=train.csv --da_type=rd
python eda_script.py --alpha=.1 --num_aug=3 --input=train.csv --da_type=rd
python eda_script.py --alpha=.1 --num_aug=5 --input=train.csv --da_type=rd
python eda_script.py --alpha=.3 --num_aug=1 --input=train.csv --da_type=rd
python eda_script.py --alpha=.3 --num_aug=3 --input=train.csv --da_type=rd
python eda_script.py --alpha=.3 --num_aug=5 --input=train.csv --da_type=rd
python eda_script.py --alpha=.5 --num_aug=1 --input=train.csv --da_type=rd
python eda_script.py --alpha=.5 --num_aug=3 --input=train.csv --da_type=rd
python eda_script.py --alpha=.5 --num_aug=5 --input=train.csv --da_type=rd

